version: "3.7"

services:
    scrapy:
        build: .
        image: brl/scrapy
        volumes:
            - .:/app/:cached
        ports:
            - 6800:6800
        networks:
            - scrapy_network
        command: scrapyd
        restart: always

    splash:
        image: scrapinghub/splash:3.4.1
        ports:
            - 8050:8050
        networks:
            - scrapy_network
        command: --max-timeout 15 --maxrss 500
        restart: always

networks:
    scrapy_network:
        name: scrapy_network
        driver: bridge
