version: '3'

services:
  scrapy:
    build: .
    image: brl/scrapy
    volumes:
      - .:/app/:cached
    ports:
      - 6800:6800
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrapy_http.rule=Host("$VIRTUAL_HOST")
      - traefik.http.routers.scrapy_http.middlewares=scrapy_auth
      - traefik.http.middlewares.scrapy_auth.basicauth.usersfile=/etc/traefik/.htpasswd
    command: scrapyd
    restart: always

  splash:
    image: scrapinghub/splash:3.4.1
    ports:
      - 8050:8050
    networks:
      - traefik_network
    command: --max-timeout 15 --maxrss 500
    restart: always
    depends_on:
      - scrapy

networks:
  traefik_network:
    external:
      name: traefik_network
