version: '3'

networks:
  traefik:
    external:
      name: traefik_network

services:
  scrapy:
    build: ./app/
    # volumes:
    #   - ./app/:/home/user/app/:cached
    expose:
      - 6800
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrapy_https.rule=Host("$VIRTUAL_HOST")
      - traefik.http.routers.scrapy_https.tls.certresolver=httpchallenge_0
      - traefik.http.routers.scrapy_https.middlewares=scrapy_auth
      - traefik.http.middlewares.scrapy_auth.basicauth.usersfile=/etc/traefik/.htpasswd
      - traefik.http.routers.scrapy_http.rule=Host("$VIRTUAL_HOST")
      - traefik.http.routers.scrapy_http.middlewares=scrapy_redirect
      - traefik.http.middlewares.scrapy_redirect.redirectscheme.scheme=https
    env_file: .env
    command: scrapyd
    restart: always

  splash:
    image: scrapinghub/splash:3.5.0
    expose:
      - 8050
    command: --max-timeout 15 --maxrss 750
    restart: always
