version: "3.7"

services:
    scrapy_main:
        container_name: scrapy_main
        build: .
        image: brl/scrapy
        ports:
            - 6800:6800
        networks:
            - scrapy_network
        command: scrapyd
        restart: always

networks:
    scrapy_network:
        name: scrapy_network
        driver: bridge
