version: "3.7"

services:
    scrapy_main:
        container_name: scrapy_main
        build: .
        image: brl/scrapy
        volumes:
            - .:/app/:cached
        ports:
            - 6800:6800
        networks:
            - scrapy_network
        command: scrapyd
        restart: always

    splash:
        container_name: splash
        image: scrapinghub/splash
        ports:
            - 8050:8050
        restart: always

networks:
    scrapy_network:
        name: scrapy_network
        driver: bridge
