version: '3'

services:
  scrapy:
    build: .
    image: brl/scrapy
    expose:
      - 6800
    networks:
      - inner_network
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrapy_https.rule=Host("$VIRTUAL_HOST")
      - traefik.http.routers.scrapy_https.tls.certresolver=httpchallenge_0
      - traefik.http.routers.scrapy_https.middlewares=scrapy_auth
      - traefik.http.middlewares.scrapy_auth.basicauth.usersfile=/etc/traefik/.htpasswd
    env_file:
      - .env
    command: scrapyd
    restart: always

  splash:
    image: scrapinghub/splash:3.4.1
    expose:
      - 8050
    networks:
      - inner_network
    command: --max-timeout 15 --maxrss 500
    restart: always
    depends_on:
      - scrapy

networks:
  inner_network:
    driver: bridge
  traefik_network:
    external:
      name: traefik_network
